export const GET_ALL_MEMBERS = "GET_ALL_MEMBERS";
export const GET_SINGLE_MEMBER = "GET_SINGLE_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const CREATE_MEMBER = "CREATE_MEMBER";
export const UPDATE_MEMBER = "UPDATE_MEMBER";